# fly.toml app configuration file generated for higgins-ai-express-api on 2024-10-18T01:35:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'higgins-ai-express-api'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
